AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchgateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: s3://artifactoutbucket/lambda_function.zip
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::637423317527:role/multirolelamda'
